node-web:
  app:
    cors: true
    assets: assets
    port: <%= port %>
    host: <%= host %>
    viewDir: view
    controllerDir: controller
  data:
<%_ if (datasource.indexOf('mongo') >= 0) { _%>
    mongo:
      -
        dao: jweb-mongo
        bean: primary
        url: mongodb://localhost:27017
        poolSize: 10
<%_ }; _%>
<%_ if (datasource.indexOf('mysql') >= 0) { _%>
    mysql:
      -
        dao: jweb-mysql
        bean: primary
        host: 127.0.0.1
        port: 3306
        user: root
        password: ''
        database: test
        connectionLimit: 10
<%_ }; _%>
<%_ if (datasource.indexOf('redis') >= 0) { _%>
    redis:
      -
        dao: jweb-redis
        bean: primary
        host: 127.0.0.1
        port: 6379
<%_ }; _%>