node-web:
  app:
    cors: true
    assets: assets
    port: 8080
    host: localhost
    viewDir: view
    controllerDir: controller
  cache:
    maxCacheSize: 104857600
    expire: 60000
  data:
    #mongo: // one connection
      # url: mongodb://localhost:27017
      #auth:
        #  user: ''
        #  password: ''
    # mongo:
    #   -
    #     dao: jweb-mongo
    #     bean: primary
    #     url: mongodb://localhost:27017
    #     poolSize: 10
     #-
        #url: mongodb://localhost:27017
    mysql:
      -
        dao: jweb-mysql
        bean: primary
        master: true
        host: 127.0.0.1
        port: 3306
        user: root
        password: 123123
        database: test
        connectionLimit: 20
    # redis:
    #   -
    #     dao: jweb-redis
    #     bean: primary
    #     host: 127.0.0.1
    #     port: 6379
